# MySQL Connection Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/stock_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 외부 API 인증키 설정
PublicDataKey=0a58be941d486a6e1b88ecc2c7aaf7a1f379a3faa403bb45c134af06101eefd1
OpenDartKey=a93cd8f3e48dd504783a0e46f930f08dd6b0c31e